# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrew Craven
tagline: '"There is one thing worse than exercise, and that is unrecorded exercise."'
sidebar_image: /images/cover.jpg
email: andrew@epworth-consulting.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Random ramblings from my experiences with .NET and related technologies
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://acraven.github.io" # the base hostname & protocol for your site
github_username: acraven
repository: acraven/acraven.github.io
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
theme: minima
